altered dl rules for url etc

diff --git a/scripts/dl b/scripts/dl
--- a/scripts/dl
+++ b/scripts/dl
@@ -1,9 +1,7 @@
 #!/bin/bash
 
-# File to store domain, download type, and default path mappings
 mapping_file=".download_mappings.txt"
 
-# Function to extract domain from URL
 extract_domain() {
     local url="$1"
     local domain
@@ -14,7 +12,6 @@ extract_domain() {
     echo "$domain"
 }
 
-# Function to prompt user for download type
 prompt_download_type() {
     local domain="$1"
     local download_type
@@ -22,7 +19,6 @@ prompt_download_type() {
     echo "$download_type"
 }
 
-# Function to prompt user for default download path
 prompt_download_path() {
     local domain="$1"
     local download_path
@@ -32,20 +28,35 @@ prompt_download_path() {
     echo "$download_path"
 }
 
-# Check if number of arguments is less than 1
-if [ "$#" -lt 1 ]; then
-    echo "Usage: $0 [command] <url>"
-    exit 1
-fi
+get_url_from_clipboard() {
+    local clipboard_content
+    clipboard_content=$(xclip -selection clipboard -o)
+    echo "$clipboard_content"
+}
 
-# Default command to "download" if not provided
+hr() {
+    local term_width
+    term_width=$(tput cols)
+    printf '%*s\n' "$term_width" '' | tr ' ' '-'
+}
+
+command=""
+url=$(get_url_from_clipboard)
+
 if [ "$#" -eq 1 ]; then
-    command=""
-    url="$1"
-else
+    command="$1"
+elif [ "$#" -eq 2 ]; then
     command="$1"
     url="$2"
 fi
+
+if [[ $url == *[$'\n\t\r']* ]]; then
+    echo $url
+    hr
+    echo "Error: url contains one or more common control characters"
+    exit 1
+fi
+
 
 # Set default download directory to user's Downloads directory
 download_path="$HOME/Downloads"
@@ -68,7 +79,7 @@ else
     echo "Added domain '$domain' with download type '$download_type' and default path '$download_path' to $mapping_file"
 fi
 
-echo "-------------------------------"
+hr
 
 case "$command" in
     download | d)
